config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: %i[show index new create edit update delete destroy]

  get 'signup', to: 'users#new'
  delete 'delete', to: 'users#destroy'
  get 'delete', to: 'users#destroy'
  resources :users, except: %i[new destroy]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'logout', to: 'sessions#destroy'

  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :title, :presence => true, length: { minimum: 6, maximum: 100 }
  validates :description, :presence => true, length: { minimum: 10, maximum: 255 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 15 }
  validates_uniqueness_of :name
  has_many :article_categories
  has_many :articles, through: :article_categories
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  has_many :articles, dependent: :destroy

  validates :username, presence: true, uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: true },
            length: { minimum: 3, maximum: 105 }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:alert] = 'You must be logged in to perform this action'
      redirect_to login_path
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_article, only: %i[show edit update destroy]
  before_action :require_user, except: %i[show index]
  before_action :require_same_user, only: %i[edit update destroy]

  def show
    @pagetitle = 'Articles'
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user
    if @article.save
      flash[:notice] = 'Article was created successfully'
      redirect_to articles_path(@article)
    else
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def get_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    if current_user != @article.user && !current_user.admin?
      flash[:alert] = 'You can only edit or delete your own article'
      redirect_to @article
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: %i[index show]
  before_action :get_category, only: %i[show edit update destroy]


  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = 'category was created successfully'
      redirect_to @category
    else
      render 'new'
    end
  end

  def index
    @category = Category.all
  end

  def show
    @articles = @category.articles
  end

  def edit

  end

  def destroy
    @category.destroy
    redirect_to categories_path
  end

  private

  def get_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = 'Only admin scan perform this function'
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    redirect_to articles_path if logged_in?
  end

  def about

  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user&.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = 'Logged in'
      redirect_to user
    else
      flash.now[:alert] = 'Incorrect username or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = 'Logged out'
    redirect_to users_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def show
    set_user
    @articles = @user.articles
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    set_user
  end

  def update
    set_user
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Alpha_Blog #{@user.username}"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all associated articles successfully deleted"
    redirect_to articles_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_same_user
    if current_user != @user
      flash[:alert] = 'permission denied'
      redirect_to @user
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/articles/_article.html.erb
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Categories</th>
      <th>Creator</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
    <tr>
      <td><%=article.title %></td>
      <td><%=article.description %></td>
      <% if article.categories.any? %>
        <td><%=render article.categories %></td>
      <% else %>
        <td> </td>
      <% end %>
      <td><%=article.user.username if article.user%></td>
      <td>
        <%=link_to 'View',article_path(article)%>
        <% if logged_in? && (article.user == current_user || current_user.admin?) %>
          <%=link_to 'Edit',edit_article_path(article)%>
          <%=link_to 'Delete',article_path(article), method: :delete, data: { confirm: 'Are you sure you want to delete this?'}%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <p>The following errors prevented the article from being saved</p>
  <% @article.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
<% end %>


<%=form_with(model: @article, local: true) do |f| %>
  <p>
    <%= f.label :title %>
    <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :description %>
    <br>
    <%= f.text_area :description %>
  </p>
  <p>
    Category (Can be Empty)
    <br>
    <%= f.collection_select(:category_ids, Category.all, :id, :name,
                            { prompt: '' }, {multiple: true}) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/_links.html.erb
<% if current_user == @article.user || current_user.admin?%>
  <%=link_to 'Edit',edit_article_path(article)%>
  <%=link_to 'Delete',article_path(article), method: :delete, data: { confirm: 'Are you sure you want to delete this?'}%>
<% end %>
<%=link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Edit <%= @article.title %></h1>

<%= render partial: 'articles/form' %>

<%=link_to 'Cancel', articles_path %>

app/views/articles/index.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>List of Articles</h1>

<%= render 'articles/article' %>

<p>
  <%= link_to 'Create new article', new_article_path %>
</p>
<p>
  <%=link_to 'Home', root_path %>
</p>

app/views/articles/new.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Create a new article</h1>

<%= render partial: 'articles/form' %>

<%=link_to 'Cancel', articles_path %>

app/views/articles/show.html.erb
<%= render partial: 'layouts/navigation' %>

<h1><%=@pagetitle %></h1>

<p><strong>Title: </strong> <%=@article.title %></p>
<p><strong>Description: </strong> <%=@article.description %></p>
<p><strong>Creator: </strong> <%=@article.user.username %></p>
<p>
  <strong>Categories: </strong>
  <br>
  <% if @article.categories.any? %>
    <%=render @article.categories %>
  <% end %>
</p>
<%= render partial: 'links', locals: { article: @article } %>

app/views/categories/_category.html.erb
<%= category.name %>

<br>

app/views/categories/_form.erb
<%=form_with(model: @category, local: true) do |f| %>
  <p>
    <%= f.label :name %>
    <br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit 'Update Category' %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Update Category</h1>

<%= render partial: 'categories/form' %>

<%=link_to 'Cancel', categories_path %>

app/views/categories/index.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Categories</h1>

<table>
  <thead>
  <tr>
    <th>Category Name</th>
  </tr>
  </thead>

  <tbody>
  <% @category.each do |category| %>
    <tr>
      <td><%=link_to category.name, category_path(category) %></td>
      <td><%= pluralize(category.articles.count, 'Articles') %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>
<br>

<%= link_to 'Create new Category', new_category_path %>

<%= link_to 'Home', root_path %>

app/views/categories/new.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>New Category</h1>

<%= render partial: 'categories/form' %>

<%=link_to 'Cancel', categories_path %>

app/views/categories/show.html.erb
<%= render partial: 'layouts/navigation' %>

<h1><%=@category.name %></h1>

<%= render 'articles/article' %>

<% if current_user.admin? %>
  <%= link_to 'Edit Category', edit_category_path(@category) %>
  <%= link_to 'Delete Category', category_path(@category), method: :delete %>
<% end %>
<br>
<%= link_to 'Back to category list', categories_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<br>
<%= link_to 'Articles', articles_path %>
<%= link_to 'Bloggers', users_path %>
<%= link_to 'Categories', categories_path %>
<% if logged_in? %>
  <%= link_to current_user.username, user_path(current_user)%>
  <%= link_to 'Log out', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Log in', login_path %>
  <%= link_to 'Sign up', signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <%= render partial: 'layouts/messages'%>
  <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>About</h1>

<p>This is the about page!</p>

<p>
  <%=link_to 'Home', root_path %>
</p>

app/views/pages/home.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Home</h1>

<p>This is the home page!</p>

<p>
  <%=link_to 'Articles', articles_path %>
</p>

<p>
  <%=link_to 'Users', users_path %>
</p>

<p>
  <%=link_to 'About', about_path %>
</p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <p>The following errors prevented the article from being saved</p>
  <% @user.errors.full_messages.each do |msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
<% end %>


<%=form_with(model: @user, local: true) do |f| %>
  <p>
    <%= f.label :username %>
    <br>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %>
    <br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.label :email %>
    <br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.submit(@user.new_record? ? 'Sign up' : 'Update Account') %>
  </p>
<% end %>

app/views/users/edit.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Edit profile</h1>

<%= render partial: 'users/form' %>

<%=link_to 'Cancel', users_path %>

app/views/users/index.html.erb
<%= render partial: 'layouts/navigation' %>

<h1> List of users </h1>

<table>
  <thead>
  <tr>
    <th>User</th>
    <th>Articles</th>
    <th>Joined</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
  <% @users.each do |user|%>
    <tr>
      <td><%=user.username %></td>
      <td><%=pluralize(user.articles.count, 'Articles') %></td>
      <td><%=user.created_at %></td>
      <td>
        <%=link_to 'View',user_path(user)%>
        <% if logged_in? && user == current_user %>
          <%=link_to 'Edit',edit_user_path(user)%>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<p>
  <%=link_to 'Home', root_path %>
</p>

app/views/users/new.html.erb
<%= render partial: 'layouts/navigation' %>

<h1>Sign Up</h1>

<%= render partial: 'users/form' %>

<%=link_to 'Cancel', articles_path %>

app/views/users/show.html.erb
<%= render partial: 'layouts/navigation' %>

<h1><%=@user.username %></h1>

<h2>Articles</h2>

<%= render 'articles/article' %>

<%= link_to 'Back to user list', users_path %>
<br>
<br>
<% if current_user == @user || current_user.admin? %>
  <% if current_user == @user %>
    <%= link_to 'Edit Account', edit_user_path(current_user) %>
  <% end %>
  <%= link_to 'Delete Account', user_path(current_user), method: :delete %>
<% end %>